=== torontojs/historical-archive/src/schemas/event.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"type": "object",
	"required": [ "title", "startDate", "endDate", "status", "locationType", "details" ],
	"properties": {
		"title": {
			"type": "string",
			"description": "The event's title."
		},
		"hosts": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of people who are hosting the event."
		},
		"startDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's start date, in ISO format."
		},
		"endDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's end date, in ISO format."
		},
		"status": {
			"enum": [ "canceled", "active" ],
			"description": "If the event was canceled or not."
		},
		"locationType": {
			"enum": [ "in-person", "virtual", "hybrid" ],
			"description": "Where the event takes place, if it is an in person, virtual, or hybrid event."
		},
		"image": {
			"type": "string",
			"format": "uri",
			"description": "An URL pointing to the event's cover image."
		},
		"details": {
			"type": "string",
			"format": "markdown",
			"description": "The event details, in markdown format."
		},
		"tags": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of tags related to the event."
		}
	}
}

=== torontojs/historical-archive/src/data/events/event-2024-02-27.json
{
  "title": "JS Tech Talk [In-Person] - Filesystems, and QwikJS",
  "hosts": [
    "Aman A.",
    "sami x."
  ],
  "startDate": "2024-02-27T18:00:00-05:00",
  "endDate": "2024-02-27T18:00:00-05:00",
  "status": "active",
  "locationType": "in-person",
  "image": "https://secure.meetupstatic.com/photos/event/a/3/3/1/600_510821777.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\"><strong>ðŸ™Œ Welcome back to our first meetup of 2024!</strong></p>\n<p class=\"mb-4\">We welcome you to our February 2024 In-Person Tech Talk Meetup at <strong><a href=\"http://Super.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Super.com</a></strong>! ðŸ‘‹</p>\n<p class=\"mb-4\">Come out and join us for a special event with our members who are coming together to share their knowledge with the community.</p>\n<p class=\"mb-4\"><strong>NOTE:</strong> RSVP on our Guild page: <a href=\"https://guild.host/events/js-tech-talk-inperson-z5zmjq\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/events/js-tech-talk-inperson-z5zmjq</a></p>\n<p class=\"mb-4\"><strong>Schedule:</strong><br>\n<strong>6:00 pm</strong> - Doors Open</p>\n<p class=\"mb-4\"><strong>6:20 pm</strong> - Welcome notes from TorontoJS</p>\n<p class=\"mb-4\"><strong>6:30 pm</strong> - Welcome from our hosts - Super.com</p>\n<p class=\"mb-4\"><strong>6:35 pm</strong> - <strong>Introduction to QwikJS : build blazing fast web apps at the Edge</strong> - by Brandon Cha<br>\nAbout Brandon: \"<em>Brandon Cha (he/him) is a Software Developer who loves exploring different cultures through food, travel, and experiences. He previously worked in development as a B2B and B2C solutions consultant primarily within the media and entertainment industry, he likes to discover and find creative solutions to solve the next challenge in web and application development from frontend to the backend. In this talk, Brandon will be sharing with us how the QwikJS framework is easy to use and setup, and why its envious Edge-optimized loading time shows us a glimpse of the future in how frontend development is built and deployed.</em>\"</p>\n<p class=\"mb-4\"><strong>7:05 pm</strong> - <strong>Introductions to File Systems</strong> - by Evert Pot<br>\nAbout Evert: \"<em>Evert Pot has been building web applications for 20 years and is currently CTO at Sprout Family. Check out his blog: <a href=\"https://evertpot.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://evertpot.com</a></em>\"</p>\n<p class=\"mb-4\"><strong>7:35 pm</strong> - Networking</p>\n<p class=\"mb-4\"><strong>9:00 pm</strong> - Doors Close</p>\n<p class=\"mb-4\">(Note: All times in the schedule are an approximation.)</p>\n<p class=\"mb-4\"><strong>Many thanks to <a href=\"http://Super.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Super.com</a> for hosting us!</strong></p>\n<p class=\"mb-4\">----</p>\n<p class=\"mb-4\">We're looking for sponsors for events like these. If you or your company would like to support TorontoJS and get a message out to our community, please get in touch with <a href=\"http://organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com</a></p>\n<p class=\"mb-4\">The <a href=\"https://torontojs.com/p/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Code of Conduct</a> is enforced at all TorontoJS events and spaces - online or in-person.</p>\n<p class=\"mb-4\">Gendered toilets and a single occupancy accessible toilet are available.<br>\nTorontoJS is a volunteer-led not-for-profit organization. Please help us with tidying up; otherwise, the venue staff and volunteers have to pick up after you.</p>\n<p class=\"mb-4\"><strong>IMPORTANT:</strong> Attendees must RSVP on Guild: <a href=\"https://guild.host/events/js-tech-talk-inperson-z5zmjq\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/events/js-tech-talk-inperson-z5zmjq</a></p></div>",
  "tags": [
    "Events in Toronto, ON",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2023-10-04.json
{
  "title": "JS Workshop for Women Developers [In Person] - RSVP Link in description!",
  "hosts": [],
  "startDate": "2023-10-04T18:00:00-04:00",
  "endDate": "2023-10-04T18:00:00-04:00",
  "status": "active",
  "locationType": "in-person",
  "image": "./images/600_515919032.webp",
  "tags": [
    "Events in Toronto, ON",
    "Public Speaking",
    "JavaScript",
    "JavaScript Libraries",
    "Women's Empowerment",
    "Technical Communicators"
  ],
  "details": "Details\n-------\n\nUnlock the power of communication at Code & Communicate: a workshop for women developers!\n\n[Register here](https://guild.host/events/code-communicate-a-workshop-vx61iq) to reserve your spot!!\n\n**The Big Picture:**\n\nJoin like-minded women to learn from experts and participate in a workshop designed to elevate your technical documentation, cross-team collaboration, and public speaking at this **in-person** event.\n\nTake advantage a supportive environment focused on the unique challenges and opportunities facing women in development and participate in three facilitated breakout sessions:\n\nMaster Technical Documentation\n\n*   Learn the art of crafting technical documentation that drives project success and get hands-on experience in creating clear, concise content.\n\nBridge the Gap with Non-Technical Teams\n\n*   Get tips on navigating the complexities of cross-team collaboration. Practice translating tech jargon into language everyone can understand.\n\nConquer Public Speaking\n\n*   Overcome stage fright and captivate your audience with confidence. Receive expert guidance and a unique opportunity to practice delivering clear, compelling presentations.\n\n**The Details:**\n\nCost: $10 - this cost will cover pizza.\n\nWho should join? - Women in software development (any level of experience).\n\nWhere? - Near Toronto’s financial core.\n\nWhat to bring? - Your laptop and an open mind!\n\n_**Space for this event is limited! [Registration](https://guild.host/events/code-communicate-a-workshop-vx61iq) and payment is required.**_\n\nStep 1: Register to attend on [Guild](https://guild.host/events/code-communicate-a-workshop-vx61iq).  \nStep 2: You will receive an email with instructions on payment.  \nStep 3: You will receive an email with venue details.\n\n**Meet the Experts:**\n\nNiya Panamdanam is a senior software engineer with over 6 years of front-end expertise. She is a passionate advocate for women in the tech industry and emphasizes the significance of thorough technical documentation and efficient technical debt management. She serves as the engineering team lead at Healthie, a healthcare SaaS firm.\n\nNatasha Kasunic is a passionate speaker who has captured all kinds of audiences including executives, peers, students, 1000+ person crowds and smaller project groups both online and in-person. She has a double degree in business and computer science and is currently a product manager at marketing tech firm, Environics Analytics.\n\n**Meet Your Hosts:**\n\nZeinab Farag is a full stack developer with about 2 years of experience. She is a career-transitioner starting off in the life sciences and breaking into the tech industry after joining a web development bootcamp. She joined TorontoJS early 2023 and is looking forward to organizing events that are as informative and exciting as the ones that have inspired her in the past.\n\nChantal Gagnon recently landed in Toronto from NYC where she spent the last decade working with aspiring entrepreneurs and companies in finance, high-ed, and tech before joining Salesforce’s innovation team where she is now. Passionate about empowering women, she co-founded a unique event series that fuses meditation and design thinking to help women confidently find their voice.\n\n[Code of Conduct](https://torontojs.com/?p=/p/code_of_conduct) is enforced at all TorontoJS events\n\nRegister [here](https://guild.host/events/code-communicate-a-workshop-vx61iq)."
}

=== torontojs/historical-archive/src/data/events/event-2023-06-28.json
{
  "title": "JS Social: Online",
  "hosts": [
    "Matthew M.",
    "Sherry Y."
  ],
  "startDate": "2023-06-28T18:00:00-04:00",
  "endDate": "2023-06-28T18:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "./images/600_510478248.webp",
  "tags": [
    "Events in",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ],
  "details": "Details\n-------\n\nWelcome, if you're new here! We've made **JS Social: Online** a regular online social event now.\n\nFriends + Code = LOVE!\n\nTorontoJS Social is our lightest event where like minds get together, have a snack or drink, and talk javascript/coding. Feel free to bring your project and questions, but there is no specific programming/talk portion to the event.\n\nWe'll be **Online** for the last Wednesday of the month! Come talk JavaScript, Development, and Community!\n\nThis event is open to all skill levels.  \nCode of conduct is enforced at all TorontoJS events [https://torontojs.com/p/code\\_of\\_conduct](https://torontojs.com/p/code_of_conduct)\n\n**Guild Trial**  \nWe're also trialing a new platform for Events & Presentations - Guild!  \nPlease register for this event on Guild by following the link below, in order to assist us with the trial. Thank you!  \n[https://beta.guild.host/events/js-social-f70z5p](https://beta.guild.host/events/js-social-f70z5p)"
}

=== torontojs/historical-archive/src/data/events/event-2023-04-27.json
{
  "title": "TorontoJS Presents: International Women's Day North America 2023 #WTMDareToBe",
  "hosts": [
    "Sherry Y.",
    "2 others"
  ],
  "startDate": "2023-04-27T12:00:00-04:00",
  "endDate": "2023-04-27T12:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/1/b/1/9/600_512046937.webp?w=750",
  "tags": [
    "Events in",
    "Engineering Leadership",
    "Personal Branding",
    "Diversity & Inclusion",
    "Professional Development",
    "Technology Startups"
  ],
  "details": "Details\n-------\n\nJoin us on YouTube Live for this returning event at TorontoJS, **TorontoJS Presents: International Women's Day North America 2023 #WTMDareToBe**.\n\nWomen Techmakers (WTM) Ambassadors are collaborating with TorontoJS again! To celebrate International Women's Day (IWD) 2023 we are going live on YouTube Live. This year's running theme from WTM is #WTMDareToBe to enhance IWD 2023 campaign theme #EmbraceEquity. A TorontoJS organizer and WTM Ambassador, Sherry Yang will be live for two hours hosting a list of speakers powered by Google and random prize draws üéÅ. Stay tuned for what's coming to your screens on April 27th!\n\nMeanwhile, checked out what happened last year in [this playlist](https://youtube.com/playlist?list=PLXoUTKvTK5ZX4THsAg-1cEmfjxh5bVuQf).\n\n**AGENDA**\n\n*   12:00 - Welcome remarks\n*   12:10 - Caitlin Morrissey + live Q&A\n*   12:40 - Janine Lee + live Q&A\n*   13:10 - Macy Kuang + live Q&A\n*   13:40 - Closing remarks\n*   14:00 - Event closed\n\n**SPEAKERS**  \nSome topics that may be covered: personal brand, inclusive teams, career journey, startup ecosystem, and team management.\n\n**Caitlin Morrissey - WTM Global Program Lead, Google**  \nAn international leader with more than a decade of experience working with Google. She supports and empowers 1,800+ leaders around the world creating an impact in their tech communities with the mission to collectively build a world where all women thrive in tech.\n\n**Janine Lee - Global L&D Strategy & Operations Leader, Google**  \nAn experienced Global L&D Leader with a background in career development, DEI, and change management. She‚Äôs a Certified Executive Coach, Adjunct Professor, and Ed.D 2023 Doctoral Candidate in Organizational Change & Leadership. Her research focuses on increasing sense of belonging for Women of Color in Technology. Janine has won dozens of international awards for her leadership and DEI efforts.\n\n**Macy Kuang - Senior Software Engineer, Miaomiao Games**  \nA well-known public speaker and Google Developer Expert for IoT and wearable technologies. With over a decade of experience in the gaming industry, Macy has made significant contributions to the development of popular games. She has earned a reputation as a leading expert in AR and VR development.\n\n**CONNECT WITH US**  \nTorontoJS - [https://torontojs.com/](https://torontojs.com/)  \nWomen Techmakers - [https://www.womentechmakers.com/](https://www.womentechmakers.com/)  \nSherry Yang - [https://twitter.com/5hel2l2y](https://twitter.com/5hel2l2y)\n\n**SOCIAL MEDIA TAGS**  \n#WTMDareToBe  \n#IWD2023  \n#EmbraceEquity\n\n**CODE OF CONDUCT**  \n[https://torontojs.com/p/code\\_of\\_conduct](https://torontojs.com/p/code_of_conduct)  \n[https://developers.google.com/community-guidelines](https://developers.google.com/community-guidelines)"
}

=== torontojs/historical-archive/src/data/events/event-2024-04-25.json
{
  "title": "TorontoJS Tech Talk [Online] - April 25th, 2024 (Apr 25, 2024)",
  "hosts": [
    "Ken B.",
    "sami x."
  ],
  "startDate": "2024-04-25T18:00:00-04:00",
  "endDate": "2024-04-25T18:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/9/e/c/f/600_520060655.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">***</p>\n<p class=\"mb-4\">üéâ <strong>TorontoJS Tech Talks are Back Online!</strong> üéâ</p>\n<p class=\"mb-4\"><strong>This Time: Exploring Cognitive Accessibility</strong></p>\n<p class=\"mb-4\">Join us for the exciting return of TorontoJS Tech Talks, now in a virtual format! This session, we're delving into \"The Current State of Cognitive Accessibility,\" a crucial topic for tech enthusiasts, developers, and anyone interested in creating more accessible and inclusive technology. Get ready for an evening of engaging discussions, learning, and networking, all from the comfort of your home.</p>\n<p class=\"mb-4\">üëã <strong>Meet Our Special Guest, Shruti Vellanki</strong></p>\n<p class=\"mb-4\">Shruti will lead a discussion on \"The Current State of Cognitive Accessibility,\" exploring its various aspects and the comprehensive guidelines established by organizations such as the W3C's COGA and Finnish Guidelines. She'll also address the challenges inherent in making technology universally accessible due to the complexity of cognitive accessibility.</p>\n<p class=\"mb-4\"><strong>About Shruti Vellanki:</strong><br>\nShruti is a dedicated Software Engineer with a passion for Front-End Development, Design Systems, Component Libraries, and Accessibility. She's also an avid reader of nonfiction and an active participant in the Toronto Public Library's Culture and Technology Bookclub. Shruti's presentation promises to offer valuable insights and practical strategies for enhancing cognitive accessibility in technology.</p>\n<p class=\"mb-4\"><strong>Event Schedule:</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li><strong>6:00 pm</strong>- Warm welcome and introduction by TorontoJS<br>\n<strong>6:10 pm</strong> - Presentation by Shruti Vellanki<br>\n<strong>6:40 pm</strong> - Interactive Q&amp;A Session<br>\n<strong>7:00 pm</strong> - Networking Opportunity<br>\n<strong>7:20 PM</strong> - Closing Remarks</li>\n</ul>\n<p class=\"mb-4\">‚≠ê <strong>Don't miss this opportunity</strong> to deepen your understanding of cognitive accessibility and its impact on technology development. This event will take place on Zoom, bringing together participants from around the world in an inspiring virtual setting.</p>\n<p class=\"mb-4\"><strong>Interested in speaking or sponsoring?</strong> Reach out to us at <a href=\"http://organizers@torontojs.com.\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com.</a><br>\nTorontoJS is committed to fostering a safe and inclusive environment for everyone, both online and at our events and spaces.<br>\n<strong>We look forward to seeing you there!</strong> üöÄ</p>\n<p class=\"mb-4\"><em>Code of Conduct is enforced online or in person at all TorontoJS events and spaces</em></p>\n<p class=\"mb-4\">We are always seeking sponsors and speakers for events similar to this one. If you or your company are interested in supporting TorontoJS or reaching our community, please contact <a href=\"http://organizers@torontojs.com.\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com.</a></p></div>",
  "tags": [
    "Events in",
    "Accessibility",
    "JavaScript",
    "Software Development",
    "Web Development",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-04-21.json
{
  "title": "Code Buddy Club: Build a Keyword Extractor: React + OpenAI API + Chakra UI",
  "hosts": [
    "Elizabeth M.",
    "2 others"
  ],
  "startDate": "2024-04-21T11:00:00-04:00",
  "endDate": "2024-04-21T11:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "./images/600_518058474.webp",
  "tags": [
    "Events in",
    "JavaScript",
    "Web Technology",
    "JavaScript Applications",
    "JavaScript Libraries"
  ],
  "details": "Details\n-------\n\n\\## What is a Code Buddy Club\n\n*   It's similar to a book club but uses free courses and tutorials instead of books\n*   Participants are free to code independently, or to pair program.\n*   Meet on discord to share progress, provide support, and help with debugging\n*   Each course should take roughly 1 - 8 weeks to complete\n*   It's a really relaxed, supportive, and social atmosphere.\n\n\\## 2024 Courses List and Schedule\n\n\\### Regular meetings\n\n*   Sundays 11am-12pm\n*   Tuesdays 6:30pm-7:30pm\n*   Location: TorontoJS Discord on the Code Buddy Channel [https://discord.com/channels/1078763949132107926/1183920018799472784](https://discord.com/channels/1078763949132107926/1183920018799472784)\n*   \\*\\* Contact us on Slack if you need a Discord Invite! [https://join.slack.com/t/torontojs/shared\\_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q](https://join.slack.com/t/torontojs/shared_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q)\n\n**Course**\n\n*   **Build a Keyword Extractor: React + OpenAI API + Chakra UI**\n*   [h](https://egghead.io/courses/javascript-internationalization-object-b62d898e)\\[ttps://[www.youtube.com/watch?v=jJNPPP2YEdM](http://www.youtube.com/watch?v=jJNPPP2YEdM)\\](https://www.youtube.com/watch?v=jJNPPP2YEdM)\n\nFull Schedule and Course List: January - June 2024:\n\n\\[code-buddy-club/Code Buddy Club [Schedule.md](http://Schedule.md) at main · torontojs/code-buddy-club ([github.com](http://github.com))\\]([https://github.com/torontojs/code-buddy-club/blob/main/Code%20Buddy%20Club%20Schedule.md](https://github.com/torontojs/code-buddy-club/blob/main/Code%20Buddy%20Club%20Schedule.md))  \n**Alt text for cover image** Rectangular graphic. Medium red background. Text says: TorontoJS, underneath inside curly brackets is three lines of text Code Buddy, then a hug happy face emoji then the word Club. There’s a stylized grey graphic of the CN tower on the left."
}

=== torontojs/historical-archive/src/data/events/event-2023-11-09.json
{
  "title": "React, Graphs, Realtime, Embeds - JS Tech Talk Night (RSVP on Guild!)",
  "hosts": [
    "dann",
    "Taz S."
  ],
  "startDate": "2023-11-09T18:45:00-05:00",
  "endDate": "2023-11-09T18:45:00-05:00",
  "status": "active",
  "locationType": "in-person",
  "image": "https://secure.meetupstatic.com/photos/event/e/1/b/3/600_516957779.webp?w=750",
  "tags": [
    "Events in Toronto, ON",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ],
  "details": "Details\n-------\n\n\\# üôå We‚Äôre back with an awesome evening of tech talks! We may even have a special discussion mixed in there too.\n\nüëã Come out and join us for a special event with some of our longest members who are coming together to share their knowledge with the community.\n\n**üéüÔ∏è RSVP now on Guild while there are places available!** Otherwise, you may be stuck on the waitlist **üëª** [https://guild.host/events/react-graphs-realtime-lcaib9](https://guild.host/events/react-graphs-realtime-lcaib9)\n\n\\## **Schedule:**\n\n**6:30pm** - Doors Open\n\n**7:00pm** - **GraphQL federation and domain modelling**\n\n**Rohan Nair** is a technology leader, software developer, angel investor and fan of humanity, with over 13 years of experience in Toronto‚Äôs technology sector. He is currently the Head of Engineering at Nautical Commerce. Rohan has been an executive at many Toronto startups, and was the Head of Technology at venture capital firm Highline Beta. His career also includes stints as a startup founder and a fractional CTO for various companies. His diverse experiences give him a unique perspective on the intersection of technology and business.\n\n**7:30pm** - **Weird Graphs** Graphs are everywhere: in our interfaces, databases, editors, queries and more. Let's look at a few and see what stories they tell us.\n\n**Dann Toliver** enjoys building things, like data structures, distributed systems, programming languages, communities of smart friendly humans, and robot pony castles with his kids.\n\n**8:00pm** - **Wait you're using React Native on the Web?!** Taz dives into the skepticism of building React Native Apps for the Web, including everything from design systems and navigation to ExpoGL and Reanimated, from how they‚Äôve successfully built Guild on top of this architecture.\n\n**Taz Singh** is the Founder of Guild and long time participant in communities around the world. He has over two decades of software experience ranging from video games & robotic AI to consumer application development, has served as a principal technical management consultant, and is a serial startup founder. When he's not behind his computer, he can be found chasing his cat around the house or being chased by cars around a race track.\n\n**8:30pm** - **Third-Party JavaScript Special Discussion** Join us with Ben Vinegar, the author of the book on \"Third-Party JavaScript\", and Taz Singh for a special discussion on the topic. This is one you won't want to miss! üëÄ\n\n**Ben Vinegar** is the General Manager of [Syntax.fm](http://Syntax.fm) at Sentry, where he also served as VP of Engineering from 2017-2021. Ben's also the co-author of Third-party JavaScript, and a contributor to O'Reilly's Beautiful JavaScript.\n\n**9:00pm** - Networking\n\n**10:00pm** - Doors Close  \nNote: All times in the schedule are an approximation.\n\n**Many thanks to VMWare for hosting us!**  \nWe're looking for sponsors for this event. If you or your company would like to support TorontoJS and get a message out to our community, please get in touch with \\[[organizers@torontojs.com](http://organizers@torontojs.com)\\]([mailto:organizers@torontojs.com](http://mailto:organizers@torontojs.com))\n\n[Code of Conduct](https://torontojs.com/p/code_of_conduct) is enforced at all TorontoJS events and spaces-online or in-person.\n\nGendered toilets and a single occupancy accessible toilet are available.\n\nTorontoJS is a volunteer-led not-for-profit organization. Kindly assist us with tidying up, as otherwise the venue staff and volunteers have to pick up after you."
}

=== torontojs/historical-archive/src/data/events/event-2023-07-26.json
{
  "title": "JS Social: Online",
  "hosts": [
    "Matthew M.",
    "Sherry Y."
  ],
  "startDate": "2023-07-26T18:00:00-04:00",
  "endDate": "2023-07-26T18:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/e/3/8/8/600_510478248.webp?w=750",
  "tags": [
    "Events in",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ],
  "details": "Details\n-------\n\nWelcome, if you're new here! We've made **JS Social: Online** a regular online social event now.\n\nFriends + Code = LOVE!\n\nTorontoJS Social is our lightest event where like minds get together, have a snack or drink, and talk javascript/coding. Feel free to bring your project and questions, but there is no specific programming/talk portion to the event.\n\nWe'll be **Online** for the last Wednesday of the month! Come talk JavaScript, Development, and Community!\n\nThis event is open to all skill levels.  \n[Code of conduct](https://torontojs.com/p/code_of_conduct) is enforced at all TorontoJS events\n\n**IMPORTANT: Guild Migration**  \nWe're migrating to a new platform for Events & Presentations - Guild!  \nPlease register for this event on [TorontoJS Guild](https://guild.host/torontojs/events)"
}
