=== torontojs/historical-archive/src/schemas/event.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"type": "object",
	"required": [ "title", "startDate", "endDate", "status", "locationType", "details" ],
	"properties": {
		"title": {
			"type": "string",
			"description": "The event's title."
		},
		"hosts": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of people who are hosting the event."
		},
		"startDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's start date, in ISO format."
		},
		"endDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's end date, in ISO format."
		},
		"status": {
			"enum": [ "canceled", "active" ],
			"description": "If the event was canceled or not."
		},
		"locationType": {
			"enum": [ "in-person", "virtual", "hybrid" ],
			"description": "Where the event takes place, if it is an in person, virtual, or hybrid event."
		},
		"image": {
			"type": "string",
			"format": "uri",
			"description": "An URL pointing to the event's cover image."
		},
		"details": {
			"type": "string",
			"format": "markdown",
			"description": "The event details, in markdown format."
		},
		"tags": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of tags related to the event."
		}
	}
}

=== torontojs/historical-archive/src/data/events/event-2024-09-28.json
{
  "title": "TorontoJS [ ONLINE ] TechTalk - Security in software releases",
  "hosts": [
    "Ken B."
  ],
  "startDate": "2024-09-28T15:00:00-04:00",
  "endDate": "2024-09-28T15:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/8/d/7/3/600_523536211.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\"># TorontoJS [ ONLINE ] TechTalk - Security in software releases: Aristide Bouix &amp; Srgjan Dimitrijevikj</p>\n<p class=\"mb-4\">ðŸ™Œ <strong>TorontoJS Tech Talks [ Online ] is back again!</strong><br>\nWe're thrilled to announce the return of TorontoJS Tech Talks to the virtual stage! In this session, we're diving into the topic of security in software releases!</p>\n<p class=\"mb-4\">ðŸ‘‹ <strong>Meet Our Special Guest,</strong><br>\n<a href=\"https://www.linkedin.com/in/aristide-bouix/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">Aristide Bouix </a>Head Of Product Security and <a href=\"https://www.linkedin.com/in/srgjan-dimitrijevikj-2a196130/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">Srgjan Dimitrijevikj </a>principle software engineering security and growth <a href=\"https://x.com/catawiki\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">@Catawiki.</a></p>\n<p class=\"mb-4\"><strong>Schedule:</strong><br>\n<strong>3:00 pm</strong>- Warm welcome and introduction by TorontoJS<br>\n<strong>3:10 pm</strong> - Presentation by our esteemed speakers.<br>\n<strong>4:00 pm</strong> - Interactive Q&amp;A Session<br>\n<strong>4:15 pm</strong> - Neworking<br>\n<strong>4:30 PM</strong> - Closing Remarks</p>\n<p class=\"mb-4\">This event will unfold on Zoom, bringing together minds from everywhere in an inspiring virtual space.</p>\n<p class=\"mb-4\">Interested in speaking or sponsoring? Let's connect at sponsor[<a href=\"http://@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">@torontojs.com</a>](<a href=\"http://mailto:organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">mailto:organizers@torontojs.com</a>).</p>\n<p class=\"mb-4\">TorontoJS is committed to creating a safe and inclusive environment for all. Our Code of Conduct applies both online and in person at all our events and spaces.</p>\n<p class=\"mb-4\">For more information on events @ TorontoJS please check out:<br>\n<a href=\"https://guild.host/torontojs/events\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/torontojs/events</a><br>\nSee you there!</p></div>",
  "tags": [
    "Events in",
    "Software Security",
    "JavaScript",
    "Functional Programming",
    "Software Development",
    "Web Development"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2023-06-29.json
{
  "title": "JS Technical Interview Prep",
  "hosts": [
    "Adam N."
  ],
  "startDate": "2023-06-29T18:30:00-04:00",
  "endDate": "2023-06-29T18:30:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/2/d/b/600_513480731.webp?w=750",
  "tags": [
    "Events in",
    "JavaScript",
    "Algorithms",
    "Computer Programming",
    "Software Development",
    "Data Structures"
  ],
  "details": "Details\n-------\n\nJoin us for an exciting series of online events focused on Data Structures and Algorithms (DSA) basics, specifically designed for aspiring junior developers! In these interactive sessions, we will delve into fundamental DSA concepts and tackle introductory interview questions that frequently come up in technical interviews. In each session, we will go over one basic concept, see how it applies to interviews, and solve 1-2 easy questions mostly on Leetcode. Don't miss out on this opportunity to enhance your skills and knowledge of technical interviews for your job search.\n\n**Code of conduct is enforced at all TorontoJS events**  \n**[https://torontojs.com/p/code\\_of\\_conduct](https://torontojs.com/p/code_of_conduct)**"
}

=== torontojs/historical-archive/src/data/events/event-2024-06-06.json
{
  "title": "Toronto JS Tech Talk Event [in person]",
  "hosts": [
    "sami x.",
    "2 others"
  ],
  "startDate": "2024-06-06T17:30:00-04:00",
  "endDate": "2024-06-06T17:30:00-04:00",
  "status": "active",
  "locationType": "in-person",
  "image": "https://secure.meetupstatic.com/photos/event/d/f/3/2/600_521097138.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">Welcome back folks, to another exciting Tech Talk event at Snowflake on June 6th! Tonight is going to be exceptional, with not one, not two, but three fantastic speakers lined up, each ready to do a <strong>30-minute talk</strong> about a variety of topics. And guess what? <strong>There will be pizza and non-alcoholic drinks waiting for you too!</strong></p>\n<p class=\"mb-4\">We are also thrilled to announce that Alex Okrushko from AngularToronto Meetup will be joining our event as one of the hosts and our MC for the evening. Make sure to mark your calendars and come out and join us for this very special event and discover what he has in store for us!</p>\n<p class=\"mb-4\">We are still finalizing the tech talks, and will update the agenda when we have more details, but here's a quick rundown of the schedule for the day:</p>\n<p class=\"mb-4\"><strong>FEATURING</strong><br>\n<strong>\"React TypeScript Patterns\"</strong> by Hassan Djirdeh<br>\n<a href=\"https://www.linkedin.com/in/hassandjirdeh/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">https://www.linkedin.com/in/hassandjirdeh/</a></p>\n<p class=\"mb-4\"><strong>\"TypeScript's Magic: Achieving End-to-End Type Safety Across the Full Stack\"</strong> by Joe Zhou<br>\n<a href=\"https://www.linkedin.com/in/zhehuizhou/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">https://www.linkedin.com/in/zhehuizhou/</a></p>\n<p class=\"mb-4\"><strong>\"Performance Optimization in <a href=\"http://Next.js:\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Next.js:</a> Tips and Techniques\"</strong> by Devang Sharma<br>\n<a href=\"https://www.linkedin.com/in/devang25/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">https://www.linkedin.com/in/devang25/</a></p>\n<p class=\"mb-4\"><strong>Schedule:</strong><br>\n<strong>5:30pm</strong> - doors \"open\"<br>\n<strong>6:00pm to 6:30pm</strong> - \"TypeScript's Magic: Achieving End-to-End Type Safety Across the Full Stack\" by Joe Zhou<br>\n<strong>6:30pm to 7:00pm</strong> - \"React TypeScript Patterns\" by Hassan Djirdeh<br>\n<strong>7:00pm to 7:30pm</strong> - 30mins break time<br>\n<strong>7:30pm to 8:00pm</strong> - \"Performance Optimization in Next.js: Tips and Techniques\" by Devang Sharma<br>\n<strong>8:00pm to 9:00pm</strong> - networking time<br>\n<strong>9:00pm</strong> - everyone goes \"home\"</p>\n<p class=\"mb-4\"><strong>Please RSVP to confirm your attendance.</strong> If you have your friends or teammates joining please ask them to RSVP as well.</p>\n<p class=\"mb-4\"><strong>You can also RSVP at Guild:</strong><br>\n<a href=\"https://guild.host/events/js-tech-talk-in-person-x0nqk7\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/events/js-tech-talk-in-person-x0nqk7</a></p>\n<p class=\"mb-4\">This event is open to all skill levels.</p>\n<p class=\"mb-4\">Many thanks to Snowflake for hosting us!</p>\n<p class=\"mb-4\">We're looking for sponsors for events like these. If you or your company would like to support TorontoJS and get a message out to our community, please get in touch with [<a href=\"http://organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com</a>](<a href=\"http://mailto:organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">mailto:organizers@torontojs.com</a>)<br>\nThe Code of Conduct is enforced at all TorontoJS events and spaces - online or in-person.</p>\n<p class=\"mb-4\">Gendered toilets and a single occupancy accessible toilet are available.<br>\nTorontoJS is a volunteer-led not-for-profit organization. Please help us with tidying up. otherwise, the venue staff and volunteers will have to pick up after you.</p></div>",
  "tags": [
    "Events in Toronto, ON",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-03-24.json
{
  "title": "TorontoJS Code Buddy Club online - Javascript Internationalization Object",
  "hosts": [
    "Elizabeth M.",
    "2 others"
  ],
  "startDate": "2024-03-24T11:00:00-04:00",
  "endDate": "2024-03-24T11:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/4/8/2/a/600_518058474.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">## What is a Code Buddy Club</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>It's similar to a book club but uses free courses and tutorials instead of books</li>\n<li>Participants are free to code independently, or to pair program.</li>\n<li>Meet on discord to share progress, provide support, and help with debugging</li>\n<li>Each course should take roughly 1 - 8 weeks to complete</li>\n<li>It's a really relaxed, supportive, and social atmosphere.</li>\n</ul>\n<p class=\"mb-4\">## 2024 Courses List and Schedule</p>\n<p class=\"mb-4\">### Regular meetings</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>Sundays 11am-12pm</li>\n<li>Tuesdays 6:30pm-7:30pm</li>\n<li>Location: TorontoJS Discord on the Code Buddy Channel <a href=\"https://discord.com/channels/1078763949132107926/1183920018799472784\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://discord.com/channels/1078763949132107926/1183920018799472784</a></li>\n<li>** Contact us on Slack if you need a Discord Invite! <a href=\"https://join.slack.com/t/torontojs/shared_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://join.slack.com/t/torontojs/shared_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q</a></li>\n</ul>\n<p class=\"mb-4\"><strong>Course</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li><strong>Javascript Internationalization Object</strong></li>\n<li><a href=\"https://egghead.io/courses/javascript-internationalization-object-b62d898e\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://egghead.io/courses/javascript-internationalization-object-b62d898e</a></li>\n</ul>\n<p class=\"mb-4\">Full Schedule and Course List: January - June 2024:</p>\n<p class=\"mb-4\">[code-buddy-club/Code Buddy Club <a href=\"http://Schedule.md\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Schedule.md</a> at main · torontojs/code-buddy-club (<a href=\"http://github.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">github.com</a>)](<a href=\"https://github.com/torontojs/code-buddy-club/blob/main/Code%20Buddy%20Club%20Schedule.md\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://github.com/torontojs/code-buddy-club/blob/main/Code%20Buddy%20Club%20Schedule.md</a>)<br>\n<strong>Alt text for cover image</strong> Rectangular graphic. Medium red background. Text says: TorontoJS, underneath inside curly brackets is three lines of text Code Buddy, then a hug happy face emoji then the word Club. There’s a stylized grey graphic of the CN tower on the left.</p></div>",
  "tags": [
    "Events in",
    "JavaScript",
    "Web Technology",
    "JavaScript Applications",
    "JavaScript Libraries"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2023-09-28.json
{
  "title": "JS Tech Talk [In Person] - RSVP Link in description!",
  "hosts": [
    "Jen C."
  ],
  "startDate": "2023-09-28T18:00:00-04:00",
  "endDate": "2023-09-28T18:00:00-04:00",
  "status": "active",
  "locationType": "in-person",
  "image": "https://secure.meetupstatic.com/photos/event/b/e/d/0/600_515868848.webp?w=750",
  "tags": [
    "Events in Toronto, ON",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ],
  "details": "Details\n-------\n\n\\# We're back! (Again, yes again)\n\nJS Tech Talk is for sharing knowledge about all things Javascript or dev-related to improve our craft and careers. Talks are open to all skill levels, but these particular talks may be suited to intermediate and staff levels.  \nCome out to **VMWare Tanzu Labs** for some juicy talks on developer experience!\n\n[Code of Conduct](https://torontojs.com/p/code_of_conduct) is enforced at all TorontoJS events and spaces-online or in-person.\n\nVenue is 2 min walk from King/Yonge\n\nGendered toilets and a single occupancy accessible toilet are available.  \nPlease do not leave trash around. Our volunteers-developers like us-have to pick it up.\n\n**[RSVP here](https://guild.host/events/js-tech-talk-in-person-yqdf9q)** [](https://guild.host/events/js-tech-talk-in-person-yqdf9q)**to reserve your spot && expedite check-in on Guild!**\n\n**Pizza sponsored by [Jen Chan](https://jenchan.biz)**\n\n**Talks**\n\n**Shruti Vellanki** - Integrating Accessibility into Your Developer Workflow  \nAccessibility can be intimidating when it's viewed as a checklist. Shruti introduces us to the POUR Framework (Percievable, Operable, Understandable and Robust) to make development more intuitive when looking at code, design specs, assets and testing features. She'll also touch on how tools can be used to make this easier: browser extensions, colour contrast checkers, screen readers and integrations for your CI/CD pipeline.\n\n**Nik LeBlanc**, \"DORA at DevCycle: Tracking engineering metrics that matter\"\n\nGoogle's DevOps Research and Assessment (DORA) research shows that the most reliable software teams typically optimize their software for four metrics, including Change Lead Time, Deployment Frequency, Change Failure Rate and Mean Time To Recovery. Nik will share insights from DORA, SPACE, and DevEx that set high performing teams apart from low performing teams.\n\n**Rob Jackiewicz**, \"Fast iteration cycles, how to get feedback and build the right thing\"\n\n**Speaker Bios**\n\n**Shruti Vellank**i is a Software Engineer who loves working on the front end, Design Systems, Component Libraries, and Accessibility. She enjoys reading nonfiction and is part of the Toronto Public Library's Culture and Technology Bookclub! [https://linktr.ee/ShrutiVellanki](https://linktr.ee/ShrutiVellanki)\n\n**Nikolas LeBlanc** is the Vice President of Engineering at DevCycle, where he spearheads technological innovation, drawing from his extensive experience in the software industry. Before joining DevCycle, he held key roles at multiple companies, including Engineering Director at Taplytics and Solutions Architect at \\[[Rangle.io](http://Rangle.io)\\]([http://rangle.io/](http://rangle.io/)), leading high-impact development projects. In addition to his technical expertise, Nikolas is an accomplished public speaker, captivating audiences with his insights on topics like DORA metrics.\n\n**Rob Jackiewicz** is a Senior Staff Engineer that has worked across roles ranging from supercomputers, system software to web based systems. All that matters to him is working as part of a team that wants to achieve greatness in any endeavour that they take on.\n\n[Wanna give a talk or workshop? Tell us about it](https://tinyurl.com/torontoJS).\n\nLike what we do? We're entirely volunteer-run! Show us some love at [OpenCollective](https://opencollective.com/torontojs)!\n\nWant to sponsor an event? reach out to [sponsor@torontojs.com](http://sponsor@torontojs.com) !\n\n\\### TorontoJS thanks [DevCycle](https://devcycle.com/) and [VMWare Tanzu Labs Toronto](https://tanzu.vmware.com/locations/toronto) for generously supporting the gathering of the community, the organizing of DIY tech talks, the enjoyment of sharing knowledge!"
}

=== torontojs/historical-archive/src/data/events/event-2023-08-30.json
{
	"title": "JS Social: Online",
	"hosts": [
		"Matthew M.",
		"Sherry Y."
	],
	"startDate": "2023-08-30T18:00:00-04:00",
	"endDate": "2023-08-30T18:00:00-04:00",
	"status": "active",
	"locationType": "virtual",
	"image": "./images/600_510478248.webp",
	"tags": [
		"Events in",
		"JavaScript",
		"JavaScript Applications",
		"JavaScript Frameworks",
		"JavaScript Libraries",
		"Web Technology"
	],
	"details": "Details\n-------\n\nWelcome, if you're new here! We've made **JS Social: Online** a regular online social event now.\n\n**IMPORTANT: Guild Migration**\n\nWe're migrating to a new platform for Events & Presentations - Guild!\n\nRegister for this event on [TorontoJS Guild](https://guild.host/torontojs/events)\n\nTorontoJS Social is our lightest event where like minds get together, have a snack or drink, and talk javascript/coding. Feel free to bring your project and questions, but there is no specific programming/talk portion to the event.\n\nWe'll be **Online** for the last Wednesday of the month! Come talk JavaScript, Development, and Community!\n\nThis event is open to all skill levels.\n\n[Code of conduct](https://torontojs.com/p/code_of_conduct) is enforced at all TorontoJS events"
}

=== torontojs/historical-archive/src/data/events/event-2024-10-21.json
{
  "title": "Accessibility for Devs Series: Online Talk and Workshop",
  "hosts": [
    "Elizabeth M.",
    "Marco C."
  ],
  "startDate": "2024-10-21T18:00:00-04:00",
  "endDate": "2024-10-21T18:00:00-04:00",
  "status": "canceled",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/3/6/2/7/600_522193863.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\"><strong>This is our third Accessibility for Devs event and the second online one!</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>Would you like to advance your career and improve your software development skills with accessibility in mind?</li>\n<li>Are you curious about accessibility (\"a11y\") but don't know where to start?</li>\n<li>Have you attended other web accessibility events, but they seem to be geared more to designers and product managers?</li>\n<li>Do you know that accessibility is becoming increasingly important for legal, business, and human rights reasons?</li>\n<li></li>\n</ul>\n<p class=\"mb-4\"><strong>Well then this is the series for you!</strong><br>\nThe Accessibility for Devs Talk &amp; Workshop Series is designed for developers and run by developers. Every event will have a live coding demo and/or hands on practice so you can level up your skills.<br>\n<strong>About</strong> <strong>Accessibility for Devs Talk &amp; Workshop Series:</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>On the third Monday of every month</li>\n<li>Alternating between online and in-person events</li>\n<li>Open to all skill levels</li>\n<li>Coding focus but no accessibility knowledge required</li>\n<li>Run by the new Accessibility Team at TorontoJS!</li>\n</ul>\n<p class=\"mb-4\"><strong>Accessibility of</strong> <strong>Accessibility for Devs Talk &amp; Workshop Series</strong>:<br>\n(Because accessibility isn't just about users!)</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>All in-person events will be wheelchair accessible and have easy access to an accessible subway station or streetcar route.</li>\n<li>Online events will have auto captioning enabled and presenters/hosts will do our best to provide described audio of visuals.</li>\n<li>Talks uploaded to YouTube will have both captions and transcripts (<em>Please note: It may take a while for the first few YouTube videos to have captions and transcripts as we are setting up the new accessibility team. We're looking for volunteers!</em>)</li>\n</ul>\n<p class=\"mb-4\">***<br>\n<strong>About TorontoJS:</strong> ‚ÑπÔ∏è<br>\n<strong>Did you know that our members and volunteers are not just in Toronto, and that we're not just JavaScript!</strong> We welcome people from any field in tech and with any level of skills - from students and those considering a career change up to seasoned professionals with decades of experience.<br>\nTorontoJS is dedicated to providing a welcoming, safe, inclusive and supportive environment for all regardless of their gender, sexual orientation, disability, physical appearance, body size, race, or religion.<br>\nPlease read the <a href=\"https://torontojs.com/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">code of conduct</a> prior to attending this meeting. <a href=\"https://torontojs.com/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://torontojs.com/code_of_conduct</a><br>\nWe welcome and encourage people who are disabled, neurodivergent, deaf/Deaf, LGBTQ2S+, and BIPOC, to attend events, get involved as members and to volunteer!<br>\n***<br>\n<strong>Connect With TorontoJS üîó</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>Website: <a href=\"https://torontojs.com/\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://torontojs.com</a></li>\n<li><a href=\"https://join.slack.com/t/torontojs/shared_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Join us on Slack!</a></li>\n<li>Follow us on LinkedIn: <a href=\"https://www.linkedin.com/company/torontojs/\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">https://www.linkedin.com/company/torontojs/</a></li>\n<li>You can also find TorontoJS events on <a href=\"http://Guild.host:\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Guild.host:</a> <a href=\"https://guild.host/torontojs/events\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/torontojs/events</a></li>\n</ul>\n<p class=\"mb-4\">***<br>\n<strong>Alt text for cover image:</strong><br>\nText: Accessibility for Devs Talk &amp; Workshop Series In-Person<br>\nTalk and Workshop<br>\nTopic: TBA<br>\nLocation: Toronto TBA<br>\nDesign: Dark theme, black background, white text on the left and centre. Top left:White universal accessibility icon<br>\nOn the right there's a stylized grey CN tower on a red background that looks like flood lights shining up from the ground.</p></div>",
  "tags": [
    "Events in",
    "Web Accessibility",
    "JavaScript",
    "Software Development",
    "Web Development",
    "Tech Talks"
  ]
}

=== torontojs/historical-archive/src/test/data/events/event-2024-08-20.json
{
  "title": "New Volunteer Information and Orientation Online Meeting!",
  "hosts": [
    "Elizabeth M.",
    "Marco C."
  ],
  "startDate": "2024-08-20T18:30:00-04:00",
  "endDate": "2024-08-20T18:30:00-04:00",
  "status": "canceled",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/c/4/9/0/600_522350320.webp?w=750",
  "tags": [
    "Events in",
    "Volunteering",
    "UX Design",
    "Accessibility",
    "Professional Women",
    "Web Development"
  ],
  "details": "Details\n-------\n\n**Do you want to be part of an awesome community that's one of the largest tech meetups in the world, while gaining career experience, building a portfolio, and developing your leadership skills and professional portfolio?**\n\nTorontoJS is recruiting volunteers for in-person, hybrid, and remote positions!\n\n**Did you know that our members and volunteers are not just in Toronto, and that we're not just JavaScript!** We welcome people from any field in tech and with any level of skills - from students and those considering a career change up to seasoned professionals with decades of experience.\n\nTorontoJS is dedicated to providing a welcoming, safe, inclusive and supportive environment for all regardless of their gender, sexual orientation, disability, physical appearance, body size, race, or religion.  \nPlease read the [code of conduct](https://torontojs.com/code_of_conduct) prior to attending this meeting. [https://torontojs.com/code\\_of\\_conduct](https://torontojs.com/code_of_conduct)\n\n**We're growing!**  \n**There's four new teams with a wide range of programs and various levels of volunteer roles:**\n\n1.  Volunteer Management Team\n2.  Accessibility Team\n3.  Design Team\n4.  Women in Tech\n\nWe also need events volunteers for both in-person and online events.\n\nCommitment for roles ranges from one evening a month and/or half an hour a week, through to leadership positions with long-term commitments.  \nAll volunteers will be invited to attend volunteer only special events including the new \"May the Fourth annual volunteer party\"!\n\nThis is a meeting for new and existing volunteers interested in positions for:\n\n*   The new Design Team,\n*   Volunteer management team,\n*   Accessibility team, and\n*   Women in Tech team (leadership)\n*   In-person and online Events,\n\nThis meeting will cover:\n\n*   History and info about TorontoJS\n*   About how TorontoJS is growing.\n*   The new Volunteer Management Software (VMS) development project.\n*   Current and future volunteer positions\n*   Timelines\n*   Expectations\n*   Volunteer benefits\n*   how these positions will help TorontoJS members and volunteers\n*   Q&A\n\n**Connect With TorontoJS**\n\n*   Website: [https://torontojs.com](https://torontojs.com)\n*   [Join us on Slack!](https://join.slack.com/t/torontojs/shared_invite/zt-zgi31snl-omO3tXSZ0Q7zqN9WBQSf8Q)\n*   Follow us on LinkedIn: [https://www.linkedin.com/company/torontojs/](https://www.linkedin.com/company/torontojs/)\n*   You can also find TorontoJS events on [Guild.host:](http://Guild.host:) [https://guild.host/torontojs/events](https://guild.host/torontojs/events)\n\nAlt text for cover image:  \nText:New Volunteer Info Meeting! Online  \nTuesday, August 20  \n6:30 PM to 7:20 PM  \nDesign: Dark theme, black background, white text on the left and centre. To the left of \"New\" is a raised hand icon. On the right there's a stylized grey CN tower on a red background that looks like flood lights shining up from the ground."
}
