=== torontojs/historical-archive/src/schemas/event.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"type": "object",
	"required": [ "title", "startDate", "endDate", "status", "locationType", "details" ],
	"properties": {
		"title": {
			"type": "string",
			"description": "The event's title."
		},
		"hosts": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of people who are hosting the event."
		},
		"startDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's start date, in ISO format."
		},
		"endDate": {
			"type": "string",
			"format": "date-time",
			"description": "The event's end date, in ISO format."
		},
		"status": {
			"enum": [ "canceled", "active" ],
			"description": "If the event was canceled or not."
		},
		"locationType": {
			"enum": [ "in-person", "virtual", "hybrid" ],
			"description": "Where the event takes place, if it is an in person, virtual, or hybrid event."
		},
		"image": {
			"type": "string",
			"format": "uri",
			"description": "An URL pointing to the event's cover image."
		},
		"details": {
			"type": "string",
			"format": "markdown",
			"description": "The event details, in markdown format."
		},
		"tags": {
			"type": "array",
			"items": { "type": "string" },
			"description": "A list of tags related to the event."
		}
	}
}

=== torontojs/historical-archive/src/data/events/event-2024-08-17.json
{
  "title": "Code Club: August Edition",
  "hosts": [
    "Mike V."
  ],
  "startDate": "2024-08-17T16:00:00-04:00",
  "endDate": "2024-08-17T16:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/6/3/8/f/600_522625487.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">No bad puns with the title this time, but we still hope to work in nice and cool projects!</p>\n<p class=\"mb-4\">So, bring yours or just join us for a fun time!</p>\n<p class=\"mb-4\"><strong>About Code Club</strong><br>\nTorontoJS Code Club is a friendly coding environment where we can bounce ideas &amp; ask questions freely while working on software challenges together.</p>\n<p class=\"mb-4\">Please bring your projects/ideas to the event, or just show up and contribute to the discussion!</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>\n<p class=\"mb-4\">We can tackle an open-source issue together. Some issues don't require much context to solve and are suitable for beginners too. This group programming event can be a great opportunity to start your open-source journey.</p>\n</li>\n<li>\n<p class=\"mb-4\">We can hack on personal projects together. Is there a bug in your software that you want to fix with the group? Is there a feature you want to add? How about some refactoring to clean up your codebase? It's fun to see how everyone has different approaches to solve these technical challenges.</p>\n</li>\n<li>\n<p class=\"mb-4\">Are you job searching? We can take a look at Leetcode-style interview questions together.</p>\n</li>\n<li>\n<p class=\"mb-4\">Countless new libraries appear in the JS ecosystem every year. We can try out a new piece of tech together and share our first impressions.</p>\n</li>\n</ul>\n<p class=\"mb-4\">This event is not about competition or achievements. Come for the pure joy of building. Everyone is welcome!</p>\n<p class=\"mb-4\"><strong>Platform</strong><br>\nThe event will be hosted on the <a href=\"https://discord.com/invite/8JxSMjrPJv\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">TorontoJS discord server,</a> on the #js-code-club channel.</p>\n<p class=\"mb-4\"><strong>Accessibility Accommodations</strong><br>\nThis is an online event on Discord, please feel free to contact us at [<a href=\"http://events@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">events@torontojs.com</a>](<a href=\"http://mailto:events@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">mailto:events@torontojs.com</a>) if you need any accommodations for the event.</p>\n<p class=\"mb-4\">Our <a href=\"https://torontojs.com/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Code of Conduct</a> is enforced at all TorontoJS events.</p></div>",
  "tags": [
    "Events in",
    "JavaScript",
    "Web Technology",
    "Software Development",
    "Social Coding",
    "Code Review"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-03-30.json
{
  "title": "TorontoJS Tech Talk [Online] - March 30th, 2024 (Mar 30, 2024)",
  "hosts": [
    "Simon C.",
    "Ken B."
  ],
  "startDate": "2024-03-30T15:00:00-04:00",
  "endDate": "2024-03-30T15:00:00-04:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/7/9/4/e/600_519571054.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\"><strong>TorontoJS Tech Talk [Online]</strong> welcomes you to an electrifying virtual gathering where tech enthusiasts unite! Prepare for an immersive experience focused on cutting-edge tech talks, insightful discussions, and vibrant connections. Our highlight? A captivating presentation led by our esteemed guest host. Join us as they lead the way through an evening of curiosity, collaboration, and a deep dive into the world of JavaScript and beyond.</p>\n<p class=\"mb-4\">ðŸ‘‹ <strong>Special Guest:</strong> John Page <strong>Topic:</strong> \"The truth behind MongoDB they don't want you to know\"</p>\n<p class=\"mb-4\">A veteran of the database industry, John joined MongoDB over 10 years ago, having spent the previous 18 years working on proprietary NoSQL document databases and search technologies for the Intelligence community. He has been a Software Engineer, Presales Architect, and Professional Services Consultant and now works in Developer Advocacy. John considers himself a full-stack engineer, having written everything from operating systems to training courses and every level in-between. Nowadays, John, a maker at heart, builds hardware and software blending MongoDB with other technologies from tiny microcontrollers to infinitely scalable cloud services to solve problems - MongoDB pays him to write and talk about them. He lives in the Scottish countryside with three Labradors, four squirrels, and various robots.</p>\n<p class=\"mb-4\">ðŸš€ <strong>Agenda:</strong></p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>3:00 PM - Introduction &amp; welcome notes from TorontoJS</li>\n<li>3:10 PM - John Page's Tech Talk on MongoDB</li>\n<li>3:40 PM - Q&amp;A Session and/or Mob Programming</li>\n<li>4:00 PM - Networking</li>\n<li>4:20 PM - Closing Remarks</li>\n</ul>\n<p class=\"mb-4\">ðŸ“§ <strong>Contact:</strong> <a href=\"http://organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com</a></p>\n<p class=\"mb-4\">Elevate your tech journey with us! Be part of an engaging experience where passion for code meets the thrill of learning. See you there!</p>\n<p class=\"mb-4\"><em>Code of Conduct is enforced online or in person at all TorontoJS events and spaces</em></p>\n<p class=\"mb-4\">We are always seeking sponsors and speakers for events similar to this one. If you or your company are interested in supporting TorontoJS or reaching our community, please contact <a href=\"http://organizers@torontojs.com.\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com.</a></p></div>",
  "tags": [
    "Events in",
    "MongoDB",
    "NoSQL",
    "JavaScript",
    "Web Development",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-02-24.json
{
  "title": "JS Code Club [Online] - February 2024",
  "hosts": [
    "Ken B."
  ],
  "startDate": "2024-02-24T16:00:00-05:00",
  "endDate": "2024-02-24T16:00:00-05:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/a/0/3/e/600_519101022.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">After taking a break for a couple of months, Code Club is back for its first event of the year!</p>\n<p class=\"mb-4\">TorontoJS Code Club is a friendly coding environment where we can bounce ideas &amp; ask questions freely while working on software challenges together.</p>\n<p class=\"mb-4\">Please bring your projects/ideas to the event, or just show up and contribute to the discussion!</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li></li>\n</ul>\n<p class=\"mb-4\">We can tackle an open-source issue together. Some issues don't require much context to solve and are suitable for beginners too. This group programming event can be a great opportunity to start your open-source journey.</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li></li>\n</ul>\n<p class=\"mb-4\">Are you job searching? We can take a look at Leetcode-style interview questions together.</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li></li>\n</ul>\n<p class=\"mb-4\">Countless new libraries appear in the JS ecosystem every year. We can try out a new piece of tech together and share our first impressions.</p>\n<p class=\"mb-4\">This event is not about competition or achievements. Come for the pure joy of building.</p>\n<p class=\"mb-4\">The event will be held on the TorontoJS <a href=\"https://discord.gg/EfVDg9prGf?event=1205954886861066300\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">discord</a>.</p>\n<p class=\"mb-4\">The <a href=\"https://torontojs.com/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">TorontoJS Code of Conduct</a> is enforced at all TorontoJS events.</p>\n<p class=\"mb-4\">Find out more information about events @ <a href=\"https://guild.host/torontojs/events\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Guild</a></p></div>",
  "tags": [
    "Events in",
    "JavaScript",
    "JavaScript Applications",
    "JavaScript Frameworks",
    "JavaScript Libraries",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2010-10-26.json
{
  "title": "Hack Night",
  "hosts": [
    "James H."
  ],
  "startDate": "2010-10-26T18:30:00-04:00",
  "endDate": "2010-10-26T18:30:00-04:00",
  "status": "active",
  "locationType": "in-person",
  "image": "./images/600_17537854.webp",
  "tags": [
    "Events in Toronto, ON"
  ],
  "details": "Details\n-------\n\n[Node.js](http://Node.js) and server-side JavaScript has taken off as of late, but perhaps not your own life. If you're like me, work, and life have got in the way and have left me a little out of the loop. Join me at The Rhino for pints and server-side JavaScript hacking."
}

=== torontojs/historical-archive/src/data/events/event-2023-05-11.json
{
	"title": "JS Code Club: In-Person - Group Programming",
	"hosts": [
		"Danny K.",
		"Matt C."
	],
	"startDate": "2023-05-11T18:00:00-04:00",
	"endDate": "2023-05-11T18:00:00-04:00",
	"status": "active",
	"locationType": "in-person",
	"image": "./images/600_512377136.webp",
	"tags": [
		"Events in Toronto, ON",
		"JavaScript",
		"JavaScript Applications",
		"JavaScript Frameworks",
		"JavaScript Libraries",
		"Web Technology"
	],
	"details": "Details\n-------\n\nHello TorontoJS members!\n\nWe're excited to announce our next in-person event on May 11th, where we'll have an evening of mob programming sessions. If you're new to our code club, this is a great opportunity to meet other developers, learn and work on interesting projects, and have fun!\n\n**Important Notes**\n\n1.  We will send out RSVP confirmation email 7 days before the event, and you can't join the event if you don't confirm your attendance. This is to ensure that we have a headcount and can plan accordingly.\n2.  If you have a project you are working on, please share with us beforehand by filling out the RSVP confirmation forms. This will allow us to save time at the event. It is okay to share your project at the event if you get a last minute idea.\n3.  [Code of Conduct](https://torontojs.com/p/code_of_conduct) is enforced at all TorontoJS events\n\n**Schedule**  \n6:00 pm - Doors open  \n6:15 pm - Announcements  \n6:25 pm - Group forming  \n6:35 pm - Mob programming session 1  \n7:35 pm - Social break  \n7:50 pm - Mob programming session 2  \n8:50 pm - Finale\n\nWe'll have two separate mob programming sessions, each lasting one hour. During the social break, you can meet other members, exchange ideas, and decide which project you'd like to work on for the second session.\n\nWanna give a talk, do a book club, or run a workshop? Tell us about it: [https://tinyurl.com/torontoJS](https://tinyurl.com/torontoJS)\n\nWanna be an event partner or sponsor? Reach out at [organizers@torontojs.com](http://organizers@torontojs.com)"
}

=== torontojs/historical-archive/src/data/events/event-2025-03-25.json
{
  "title": "Bringing Animations to Life: Interactive dotLottie with JavaScript 🚀",
  "hosts": [
    "Aman A.",
    "Mariana R."
  ],
  "startDate": "2025-03-25T18:00:00-04:00",
  "endDate": "2025-03-25T18:00:00-04:00",
  "status": "active",
  "locationType": "in-person",
  "image": "https://secure.meetupstatic.com/photos/event/8/a/f/1/600_526655569.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\"><strong>In this hands-on free workshop, we’ll explore the power of dotLottie, the lightweight, flexible animation format that enhances web performance and interactivity.</strong> You'll learn how to integrate dotLottie animations seamlessly into your JavaScript projects and take them beyond static visuals by adding real-time user interactions using event-driven techniques.</p>\n<p class=\"mb-4\">By the end of this workshop, you’ll be able to:</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li>Load and control dotLottie animations dynamically in JavaScript</li>\n<li>Trigger animations based on user inputs (scroll, hover, clicks, and more)</li>\n<li>Optimize animations for smooth performance and responsiveness</li>\n<li>Use dotLottie in real-world applications (websites, apps, UI elements)</li>\n</ul>\n<p class=\"mb-4\">Whether you're a developer, designer, or UI/UX enthusiast, this session will equip you with practical skills to elevate your animations and create engaging web experiences with ease.</p>\n<p class=\"mb-4\"><strong>Meet Our Speaker</strong>✨</p>\n<p class=\"mb-4\"><strong>Karin Fam - Tech Lead at LottieFiles</strong><br>\nCurious software engineer looking to change the world, one \"Hello, world!\" at a time. Currently passionate about making pixels move themselves.</p>\n<p class=\"mb-4\"><strong>Our Schedule</strong> ✨</p>\n<ul class=\"pl-5 list-disc mb-4\">\n<li><strong>6:00 pm</strong> - Doors Open: Check-in, welcome, Food &amp; Beverages 🕕🍕</li>\n<li><strong>6:25 pm</strong> - Welcome by TorontoJS and Sponsors 💻</li>\n<li><strong>6:30 pm</strong> - Workshop begins 💻</li>\n<li><strong>7:45 pm</strong> - Interactive Q&amp;A Session ❓</li>\n<li><strong>8:00 pm</strong> - Networking 🤝</li>\n<li><strong>9:00 pm</strong> - Doors Close 🚪</li>\n</ul>\n<p class=\"mb-4\">For more information on events @ TorontoJS please check out:<br>\n<a href=\"https://guild.host/torontojs/events\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">https://guild.host/torontojs/events</a></p>\n<p class=\"mb-4\"><em>TorontoJS is committed to creating a safe and inclusive environment for all. Our Code of Conduct applies both online and in person at all our events and spaces.</em></p>\n<p class=\"mb-4\">See you there! 🎉</p></div>",
  "tags": [
    "Events in Toronto, ON",
    "Motion Graphics",
    "Animation",
    "JavaScript",
    "JavaScript Applications",
    "Web Technology"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-02-29.json
{
  "title": "JS Tech Talk[Online]: Hussien Khayoon React Testing",
  "hosts": [
    "Ken B.",
    "sami x."
  ],
  "startDate": "2024-02-29T18:30:00-05:00",
  "endDate": "2024-02-29T18:30:00-05:00",
  "status": "active",
  "locationType": "virtual",
  "image": "https://secure.meetupstatic.com/photos/event/a/1/6/b/600_517481323.webp?w=750",
  "details": "<div class=\"flex items-center justify-between\"><h2 class=\"text-xl font-semibold\">Details</h2></div><div class=\"break-words\"><p class=\"mb-4\">ðŸ™Œ TorontoJS tech talks are now online!</p>\n<p class=\"mb-4\"><strong>TorontoJS Tech Talk [Online]</strong> welcomes you to an electrifying virtual gathering where tech enthusiasts unite! Prepare for an immersive experience focused on cutting-edge tech talks, insightful discussions, and vibrant connections. Our highlight? A captivating presentation led by our esteemed guest host. Join us as they lead the way through an evening of curiosity, collaboration, and a deep dive into the world of JavaScript and beyond. Elevate your tech journey with us, and be part of an engaging experience where passion for code meets the thrill of learning.</p>\n<p class=\"mb-4\">ðŸ‘‹ Come out and join us with special guest <a href=\"https://twitter.com/hussien_coding\" target=\"_blank\" class=\"!text-viridian\" rel=\"ugc\">Hussien Khayoon</a> who will lead a talk on React Testing.</p>\n<p class=\"mb-4\">Hussien is a Staff Developer at Shopify. He has over 12 years of full-stack experience with a particular soft spot for React. He also mentors for a coding boot camp and loves helping beginners break into tech.</p>\n<p class=\"mb-4\">Hussien will be talking about testing with React to build high-quality software.</p>\n<p class=\"mb-4\"><strong>Schedule:</strong></p>\n<p class=\"mb-4\"><strong>6:30 pm</strong> - Introduction &amp; welcome notes from TorontoJS<br>\n<strong>6:40 pm</strong> - Hussien Khayoon<br>\n<strong>7:10 pm</strong> - Question Period and or mob programming<br>\n<strong>7:25 pm</strong> - Networking<br>\n<strong>7:40 PM</strong> - Final words</p>\n<p class=\"mb-4\"><strong>We look forward to seeing you!</strong></p>\n<p class=\"mb-4\">The event will be held on <a href=\"https://zoom.us/j/93451964000\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">zoom</a>.</p>\n<p class=\"mb-4\">We're always looking for speakers and sponsors for our events. Reach to us @ [<a href=\"http://organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">organizers@torontojs.com</a>](<a href=\"http://mailto:organizers@torontojs.com\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">mailto:organizers@torontojs.com</a>)</p>\n<p class=\"mb-4\">Learn more about all our <a href=\"https://guild.host/torontojs/events\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">events</a></p>\n<p class=\"mb-4\"><a href=\"https://torontojs.com/p/code_of_conduct\" target=\"_blank\" class=\"!text-viridian\" rel=\"nofollow ugc\">Code of Conduct</a> is enforced online or in person at all TorontoJS events and spaces.</p></div>",
  "tags": [
    "Events in",
    "JavaScript",
    "Open Source",
    "JavaScript Frameworks",
    "Software Engineering",
    "Web Development"
  ]
}

=== torontojs/historical-archive/src/data/events/event-2024-10-31.json
{
	"title": "TorontoJS [ ONLINE ] TechTalk - CTO Roles and responsibiliies: Ahmad Nassri",
	"hosts": [
		"Ken B."
	],
	"startDate": "2024-10-31T18:30:00-04:00",
	"endDate": "2024-10-31T18:30:00-04:00",
	"status": "active",
	"locationType": "virtual",
	"image": "./images/600_523977525.webp",
	"tags": [
		"Events in",
		"Leadership",
		"JavaScript",
		"Chief Technology Officer",
		"Technology Startups",
		"CIO / CTO"
	],
	"details": "Details\n-------\n\nðŸ™Œ **TorontoJS Tech Talks \\[ Online \\] is back again!**\n\nWe're thrilled to announce the return of TorontoJS Tech Talks to the virtual stage! In this session, we're diving into the topic CTO's and their responsibilities!\n\nðŸ‘‹ **Meet Our Special Guest,**  \n[Ahmad Nassri](https://www.linkedin.com/in/ahmadnassri/)\n\n**Schedule:**  \n**6:30 pm**\\- Warm welcome and introduction by TorontoJS  \n**6:10 pm** - Presentation by our esteemed speaker.  \n**7:00 m** - Interactive Q&A Session  \n**7:15 pm** - Neworking  \n**8:00 PM** - Closing Remarks\n\nThis event will unfold on Zoom, bringing together minds from everywhere in an inspiring virtual space.\n\nInterested in speaking, voluntering or sponsoring? Let's connect at ken\\[[@torontojs.com](http://@torontojs.com)\\]([mailto:organizers@torontojs.com](http://mailto:organizers@torontojs.com)).\n\nTorontoJS is committed to creating a safe and inclusive environment for all. Our Code of Conduct applies both online and in person at all our events and spaces.\n\nFor more information on events @ TorontoJS please check out:  \n[https://guild.host/torontojs/events](https://guild.host/torontojs/events)\n\nSee you there!"
}
